spring.application.name=springauth
server.port = 8080
#PostgresDatabase Configuration
spring.datasource.url= jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=kMSGPIBnxogcXkabNjVzvgzUFTQPyKeB
#------------------------
#Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


sendgrid.api.key=${SENDGRID_API_KEY}
security.jwt.secret-key=YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNmZGFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNmZGFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2Rm
security.jwt.expiration-time=300000
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.yourpackage=DEBUG

spring.sql.init.mode=always
