spring.application.name=springauth
server.port = 1010
#PostgresDatabase Configuration
spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=abcd
#------------------------
#Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


sendgrid.api.key=${SENDGRID_API_KEY}
security.jwt.secret-key=YXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNmZGFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2RmYXNmZGFzZGZhc2RmYXNkZmFzZGZhc2RmYXNkZmFzZGZhc2Rm
security.jwt.expiration-time=300000
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.yourpackage=DEBUG
